### PR TITLE
add deployment repo updating

### PR DESCRIPTION
**Pull request by DaytonG**
I removed the envbuild variable because a docker container is configured based on env vars or other input, so it may go to all 3 of our environments.

Also tweaked the trigger branches to match our server branch strategy document (WIP).

### CODE REVIEW

**Comment by jvilhuber** [comment]
I suggest the env-file is moved to the deployment repo and passed to the container at run time. I suspect the `npx jskit make` step might also need to be done at that time if it's needed for this 'make' step. It's not appropriate to 'bake in' deployment settings at build time (which is what the pipelines are). Deployment settings need to be passed at run time in the deployment.
This isn't really an atypical deployment as much as a typical nodejs app (where the build isn't really a build).

**Comment by owenpshaw** [comment]
I hadn't considered doing a build inside each container because it won't work today without changes to my framework (at the very least we'd end up with different named files on different containers due to http cache busting features).  But if the changes are small then we could go that way.  I need to do a little more digging.

And if there's a way to do this without a container, I'm open to ideas.  Really the only requirement is a static http server that sets the correct headers.  No need to get caught up on the definition of a proper container if that's the only problem here.

If browsers knew what to do with it, the output of this build would be some kind of installer file, which I imagine would have settings baked in.  That's why I view it as an atypical case, because the container in my mind is really more like the installer files we build for the native clients than a traditional container that is meant to be deployed across multiple environments.  In that sense, it's probably an abuse of the container system, but it seemed like a way to get what we needed with little pain.

**Comment by owenpshaw** [comment]
Ok, made a change to jskit so it can do identical builds at different times, which should allow for in-container builds now.

To do a build from the repo root, you'll need `node` installed.  Then:

````
$ npm install
$ npx jskit make --bundle-version ABC --build-label XYZ MorphicCommunityWeb --no-tag --no-docker
$ nginx -p builds/org.raisingthefloor.MorphicCommunityWeb/latest/MorphicCommunityWeb
````

* I suppose the `npm install` could happen in the Dockerfile or the container entry script.  You know best.  Note this needs to be a dev install, so you may need to do `npm install --production=false` depending on what the environment defaults to
* The `--bundle-version` should be something like 1.2.3 or 1.2.34.  If you pass the `$(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)` version the pipeline currently uses, that'd be fine
* The `--build-label` is probably easiest if it's just the version again.
* If you want to get fancy, the `nginx` command should be output by `jskit make`, but hardcoding to `latest` should work too.  (Technically the `org.raisingthefloor.MorphicCommunityWeb` part could change in a later release, but it's unlikely)
* Environment variables will be used by `jskit make` to populate app settings, so no need for an .env file unless it's helpful
  * MORPHIC_SERVER_URL (point to the temp dev api server we talked about)
  * STRIPE_PUBLIC_KEY (can be empty for now)

Also please keep the `MorphicCommunityWeb/Dockefile` as-is so local development continues as-is.  A new toplevel `Dockerfile` for deployment would be fine.

**Comment by DaytonG** [comment]
Think I've addressed the changes. Gonna merge so I can verify deployment

**Pull request merged**
